# Generated by Django 3.1.5 on 2021-02-10 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0002_auto_20210210_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='prix',
        ),
        migrations.AddField(
            model_name='livre',
            name='datePub',
            field=models.CharField(default='février 1829', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livre',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livres', to='livres.auteur'),
        ),
    ]
